server:
  port: 0

spring:
  application:
    name: auth-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    token:
      secret-key: 1a27dbb9701ab63e0eb065105468650da17d58f28ca25aae61b5927260866868cda612b26af8f95feac91928c583144a62f15bba616df8679c2734b2577edd85
